export const deeplLanguages = {
  "BG": "Bulgarian",
  "CS": "Czech",
  "DA": "Danish",
  "DE": "German",
  "EL": "Greek",
  "ES": "Spanish",
  "ET": "Estonian",
  "FI": "Finnish",
  "FR": "French",
  "HU": "Hungarian",
  "IT": "Italian",
  "JA": "Japanese",
  "LT": "Lithuanian",
  "LV": "Latvian",
  "NL": "Dutch",
  "PL": "Polish",
  "PT-PT": "Portuguese (all Portuguese varieties excluding Brazilian Portuguese)",
  "PT-BR": "Portuguese (Brazilian)",
  "PT": "Portuguese (unspecified variant for backward compatibility; please select PT-PT or PT-BR instead)",
  "RO": "Romanian",
  "RU": "Russian",
  "SK": "Slovak",
  "SL": "Slovenian",
  "SV": "Swedish",
  "ZH": "Chinese"
}